### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [antropovaa/TetrisSolver#1]
1. Поменял `Randomizer` чтобы он всегда отдавал S-фигуры, получился такой глитч:
![Imgur](https://i.imgur.com/GsvwMyw.png)

2. Иногда ряды не исчезают или исчезают не сразу. Это легко увидеть, если заставить рандомайзер возвращать только квадраты. Нижние два ряда почему-то постоянно будут на месте.

3. Тип фигурки лучше задать в виде перечисления с полями, чем в виде целого числа.

4. Есть метод `Collections.shuffle` (правда, для коллекций), можно в рандомайзере использовать его.

5. Хотелось бы ещё рандомайзер, который возвращает случайную фигуру (без учёта предыдущих). Можно сделать несколько рандомайзеров на выбор (хотя бы чтобы их было легко переключить в коде).

6. Ещё хотелось бы чтобы можно было легко регулировать количество известных следующих фигур, учитываемых в решателе (опять таки, хотя бы из кода, GUI для этой штуки не приоритетно)

7. Метод `rotateCells` попробуйте обобщить, вроде должно быть не сложно.

**Comment by antropovaa** [comment]
Некорректная работа решателя в случае пунктов 1 и 2 связана напрямую с методом "решения", так как он завязан только на определенный генератор, который я использовала в своей работе. Для других генераторов необходимо будет пересчитать коэффициенты в функции для выбора наилучшего положения, поэтому и пункт 5, наверное, будет трудно осуществим именно на практике, но в коде конечно это можно отобразить, только ведь в этом тогда не будет смысла

**Comment by antropovaa** [comment]
3, 4, 6 - исправила 
7 попробовала, но как-то неудачно, хотя вроде должно все правильно работать
